server:
  port: 8081

spring:
  datasource:
    url:
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: order-service
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  instance:
    hostname: localhost
    nonSecurePort: 8081
    preferIpAddress: false
    metadataMap:
      instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
