server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    username: postgres
    password: al5gtuv*
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: order-service
  cloud:
    compatibility-verifier:
      enabled: false

eureka:
  instance:
    hostname: localhost  # Doar numele gazdei, fără port sau nume serviciu
    nonSecurePort: 8081  # Specifică portul aici, dacă este necesar
    preferIpAddress: false  # Preferă numele gazdei, nu adresa IP
    metadataMap:
      instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
